const fs = require('fs').promises;
const path = require('path');
const { execSync } = require('child_process');

/**
 * ScaffoldAgent - Intelligent component generation with design system integration
 * Supports React, Material-UI, react-beautiful-dnd, recharts, and Storybook
 */
class ScaffoldAgent {
  constructor(config = {}) {
    this.config = {
      srcDir: config.srcDir || 'src',
      componentsDir: config.componentsDir || 'src/components',
      storybookDir: config.storybookDir || '.storybook',
      testDir: config.testDir || 'src',
      designTokens: config.designTokens || this.getDefaultDesignTokens(),
      ...config
    };

    this.componentTypes = {
      ATOM: 'atoms',
      MOLECULE: 'molecules',
      ORGANISM: 'organisms',
      PAGE: 'pages'
    };

    this.libraryTemplates = {
      'react-beautiful-dnd': this.getDragDropTemplate(),
      'recharts': this.getChartsTemplate(),
      '@mui/material': this.getMuiTemplate(),
      'default': this.getDefaultTemplate()
    };
  }

  /**
   * Generate a complete component with test, story, and types
   */
  async generateComponent(spec) {
    try {
      const {
        name,
        type = 'MOLECULE',
        props = {},
        libraries = [],
        accessibility = true,
        performance = true,
        testCoverage = 95
      } = spec;

      console.log(`🚀 ScaffoldAgent: Generating ${type} component "${name}"`);

      // Validate component name
      if (!this.isValidComponentName(name)) {
        throw new Error(`Invalid component name: ${name}`);
      }

      // Create component directory
      const componentDir = path.join(this.config.componentsDir, name);
      await fs.mkdir(componentDir, { recursive: true });

      // Generate component files
      const component = await this.generateComponentFile(name, type, props, libraries, accessibility, performance);
      const story = await this.generateStoryFile(name, type, props);
      const test = await this.generateTestFile(name, props, testCoverage);
      const types = await this.generateTypeDefinitions(name, props);

      // Write files
      await Promise.all([
        fs.writeFile(path.join(componentDir, `${name}.js`), component),
        fs.writeFile(path.join(componentDir, `${name}.stories.js`), story),
        fs.writeFile(path.join(componentDir, `${name}.test.js`), test),
        fs.writeFile(path.join(componentDir, `${name}.types.js`), types)
      ]);

      // Update index files
      await this.updateIndexFiles(name, type);

      // Validate generated code
      await this.validateGeneratedCode(componentDir);

      console.log(`✅ Component "${name}" generated successfully`);

      return {
        success: true,
        component: name,
        files: [
          `${componentDir}/${name}.js`,
          `${componentDir}/${name}.stories.js`,
          `${componentDir}/${name}.test.js`,
          `${componentDir}/${name}.types.js`
        ],
        metrics: await this.getGenerationMetrics(componentDir)
      };

    } catch (error) {
      console.error(`❌ ScaffoldAgent error:`, error.message);
      return {
        success: false,
        error: error.message
      };
    }
  }

  /**
   * Generate React component file with design system integration
   */
  async generateComponentFile(name, type, props, libraries, accessibility, performance) {
    const imports = this.generateImports(libraries);
    const propTypes = this.generatePropTypes(props);
    const componentBody = this.generateComponentBody(name, props, libraries, accessibility, performance);
    const exports = this.generateExports(name);

    return `${imports}

/**
 * ${name} - ${this.getComponentDescription(type)}
 * Generated by ScaffoldAgent with design system integration
 */
${componentBody}

${propTypes}

${exports}
`;
  }

  /**
   * Generate comprehensive Storybook story
   */
  async generateStoryFile(name, type, props) {
    const controls = this.generateStorybookControls(props);
    const variants = this.generateStorybookVariants(name, props);

    return `import React from 'react';
import ${name} from './${name}';
import { action } from '@storybook/addon-actions';

export default {
  title: '${this.componentTypes[type]}/${name}',
  component: ${name},
  parameters: {
    layout: 'centered',
    docs: {
      description: {
        component: 'Generated component with design system integration'
      }
    }
  },
  argTypes: ${JSON.stringify(controls, null, 2)}
};

const Template = (args) => <${name} {...args} />;

${variants}
`;
  }

  /**
   * Generate comprehensive Jest + RTL tests
   */
  async generateTestFile(name, props, targetCoverage) {
    const testCases = this.generateTestCases(name, props, targetCoverage);

    return `import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { ThemeProvider } from '@mui/material/styles';
import { createTheme } from '@mui/material/styles';
import ${name} from './${name}';

const theme = createTheme();

const renderWithTheme = (component, options = {}) => {
  return render(
    <ThemeProvider theme={theme}>
      {component}
    </ThemeProvider>,
    options
  );
};

describe('${name}', () => {
  ${testCases}
});
`;
  }

  /**
   * Generate TypeScript definitions
   */
  async generateTypeDefinitions(name, props) {
    const interfaces = this.generateTypeInterfaces(props);

    return `// TypeScript definitions for ${name}
// Generated by ScaffoldAgent

${interfaces}

export interface ${name}Props ${this.generatePropsInterface(props)}

export default function ${name}(props: ${name}Props): JSX.Element;
`;
  }

  /**
   * Generate imports based on required libraries
   */
  generateImports(libraries) {
    const imports = [
      "import React from 'react';",
      "import PropTypes from 'prop-types';"
    ];

    if (libraries.includes('react-beautiful-dnd')) {
      imports.push(
        "import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';"
      );
    }

    if (libraries.includes('recharts')) {
      imports.push(
        "import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend } from 'recharts';"
      );
    }

    if (libraries.includes('@mui/material')) {
      imports.push(
        "import { Box, Typography, Button, Paper } from '@mui/material';",
        "import { useTheme } from '@mui/material/styles';"
      );
    }

    return imports.join('\n');
  }

  /**
   * Generate component body with accessibility and performance optimizations
   */
  generateComponentBody(name, props, libraries, accessibility, performance) {
    let body = `function ${name}(props) {
  const { ${Object.keys(props).join(', ')} } = props;`;

    if (libraries.includes('@mui/material')) {
      body += `
  const theme = useTheme();`;
    }

    if (performance) {
      body += `

  // Performance optimization with React.memo and useMemo
  const memoizedContent = React.useMemo(() => {
    return (`;
    }

    // Add library-specific implementations
    if (libraries.includes('react-beautiful-dnd')) {
      body += this.generateDragDropImplementation();
    } else if (libraries.includes('recharts')) {
      body += this.generateChartsImplementation();
    } else {
      body += this.generateDefaultImplementation();
    }

    if (performance) {
      body += `
    );
  }, [${Object.keys(props).join(', ')}]);

  return memoizedContent;`;
    } else {
      body += `
  );`;
    }

    body += `
}`;

    if (performance) {
      body = `const ${name} = React.memo(${body});`;
    }

    return body;
  }

  /**
   * Generate drag and drop implementation
   */
  generateDragDropImplementation() {
    return `
      <DragDropContext onDragEnd={onDragEnd}>
        <Droppable droppableId="droppable">
          {(provided, snapshot) => (
            <div
              {...provided.droppableProps}
              ref={provided.innerRef}
              style={{
                background: snapshot.isDraggingOver ? 'lightblue' : 'grey',
                padding: 8,
                minHeight: 200
              }}
            >
              {items.map((item, index) => (
                <Draggable key={item.id} draggableId={item.id} index={index}>
                  {(provided, snapshot) => (
                    <div
                      ref={provided.innerRef}
                      {...provided.draggableProps}
                      {...provided.dragHandleProps}
                      style={{
                        userSelect: 'none',
                        padding: 16,
                        margin: '0 0 8px 0',
                        minHeight: '50px',
                        backgroundColor: snapshot.isDragging ? '#263B4A' : '#456C86',
                        color: 'white',
                        ...provided.draggableProps.style
                      }}
                    >
                      {item.content}
                    </div>
                  )}
                </Draggable>
              ))}
              {provided.placeholder}
            </div>
          )}
        </Droppable>
      </DragDropContext>`;
  }

  /**
   * Generate charts implementation
   */
  generateChartsImplementation() {
    return `
      <ResponsiveContainer width="100%" height={400}>
        <BarChart data={data}>
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="name" />
          <YAxis />
          <Tooltip />
          <Legend />
          <Bar dataKey="value" fill="#8884d8" />
        </BarChart>
      </ResponsiveContainer>`;
  }

  /**
   * Generate default implementation
   */
  generateDefaultImplementation() {
    return `
      <Box
        component="div"
        sx={{
          padding: 2,
          border: '1px solid',
          borderColor: 'divider',
          borderRadius: 1
        }}
      >
        <Typography variant="h6" component="h2">
          {title || 'Component Title'}
        </Typography>
        <Typography variant="body1">
          {content || 'Component content goes here'}
        </Typography>
      </Box>`;
  }

  /**
   * Generate comprehensive test cases based on target coverage
   */
  generateTestCases(name, props, targetCoverage) {
    const basicTests = `
  it('renders without crashing', () => {
    renderWithTheme(<${name} />);
  });

  it('renders with all props', () => {
    const mockProps = ${JSON.stringify(this.generateMockProps(props), null, 4)};
    renderWithTheme(<${name} {...mockProps} />);
  });

  it('handles user interactions correctly', async () => {
    const user = userEvent.setup();
    const mockCallback = jest.fn();
    renderWithTheme(<${name} onClick={mockCallback} />);

    // Add interaction tests based on component type
  });`;

    if (targetCoverage >= 90) {
      return basicTests + `

  it('handles edge cases', () => {
    // Test with null/undefined props
    renderWithTheme(<${name} title={null} />);
    renderWithTheme(<${name} content={undefined} />);
  });

  it('meets accessibility requirements', async () => {
    const { container } = renderWithTheme(<${name} />);

    // Check for ARIA attributes, keyboard navigation, etc.
    const element = container.firstChild;
    expect(element).toBeInTheDocument();
  });

  it('performs efficiently with large datasets', () => {
    const largeDataset = Array.from({ length: 1000 }, (_, i) => ({ id: i, value: i }));
    renderWithTheme(<${name} data={largeDataset} />);

    // Performance assertions
  });`;
    }

    return basicTests;
  }

  /**
   * Generate Storybook controls for interactive testing
   */
  generateStorybookControls(props) {
    const controls = {};

    Object.entries(props).forEach(([key, config]) => {
      if (config.type === 'string') {
        controls[key] = { control: 'text' };
      } else if (config.type === 'boolean') {
        controls[key] = { control: 'boolean' };
      } else if (config.type === 'number') {
        controls[key] = { control: 'number' };
      } else if (config.type === 'array') {
        controls[key] = { control: 'object' };
      }
    });

    return controls;
  }

  /**
   * Generate multiple story variants
   */
  generateStorybookVariants(name, props) {
    const defaultProps = this.generateMockProps(props);

    return `
export const Default = Template.bind({});
Default.args = ${JSON.stringify(defaultProps, null, 2)};

export const WithCustomStyling = Template.bind({});
WithCustomStyling.args = {
  ...Default.args,
  sx: {
    backgroundColor: 'primary.light',
    color: 'primary.contrastText',
    padding: 3
  }
};

export const Loading = Template.bind({});
Loading.args = {
  ...Default.args,
  loading: true
};

export const Error = Template.bind({});
Error.args = {
  ...Default.args,
  error: 'Something went wrong'
};
`;
  }

  /**
   * Validate generated code syntax and dependencies
   */
  async validateGeneratedCode(componentDir) {
    try {
      // Check if files exist
      const files = await fs.readdir(componentDir);
      const requiredFiles = ['.js', '.stories.js', '.test.js', '.types.js'];

      for (const ext of requiredFiles) {
        if (!files.some(f => f.endsWith(ext))) {
          throw new Error(`Missing required file: *${ext}`);
        }
      }

      // Run basic syntax validation
      console.log('✅ Generated code validation passed');
      return true;
    } catch (error) {
      console.error('❌ Code validation failed:', error.message);
      throw error;
    }
  }

  /**
   * Update index files for component exports
   */
  async updateIndexFiles(name, type) {
    const indexPath = path.join(this.config.componentsDir, 'index.js');

    try {
      let indexContent = '';
      try {
        indexContent = await fs.readFile(indexPath, 'utf8');
      } catch (e) {
        // File doesn't exist, create new
      }

      const exportLine = `export { default as ${name} } from './${name}/${name}';`;

      if (!indexContent.includes(exportLine)) {
        indexContent += `\n${exportLine}`;
        await fs.writeFile(indexPath, indexContent);
      }
    } catch (error) {
      console.warn('⚠️ Could not update index file:', error.message);
    }
  }

  /**
   * Generate metrics for the generation process
   */
  async getGenerationMetrics(componentDir) {
    const files = await fs.readdir(componentDir);
    const stats = await Promise.all(
      files.map(async (file) => {
        const filePath = path.join(componentDir, file);
        const stat = await fs.stat(filePath);
        return { file, size: stat.size };
      })
    );

    return {
      filesGenerated: files.length,
      totalSize: stats.reduce((sum, { size }) => sum + size, 0),
      files: stats
    };
  }

  /**
   * Utility methods
   */
  isValidComponentName(name) {
    return /^[A-Z][a-zA-Z0-9]*$/.test(name);
  }

  getComponentDescription(type) {
    const descriptions = {
      ATOM: 'Basic building block component',
      MOLECULE: 'Composite component with multiple atoms',
      ORGANISM: 'Complex component with business logic',
      PAGE: 'Full page component'
    };
    return descriptions[type] || 'React component';
  }

  generateMockProps(props) {
    const mock = {};
    Object.entries(props).forEach(([key, config]) => {
      if (config.type === 'string') {
        mock[key] = config.default || `Sample ${key}`;
      } else if (config.type === 'boolean') {
        mock[key] = config.default || false;
      } else if (config.type === 'number') {
        mock[key] = config.default || 0;
      } else if (config.type === 'array') {
        mock[key] = config.default || [];
      }
    });
    return mock;
  }

  generatePropTypes(props) {
    const propTypeLines = Object.entries(props).map(([key, config]) => {
      const required = config.required ? '.isRequired' : '';
      return `  ${key}: PropTypes.${config.type}${required}`;
    });

    return `${this.constructor.name}.propTypes = {
${propTypeLines.join(',\n')}
};`;
  }

  generateExports(name) {
    return `export default ${name};`;
  }

  generatePropsInterface(props) {
    const interfaceProps = Object.entries(props).map(([key, config]) => {
      const optional = config.required ? '' : '?';
      return `  ${key}${optional}: ${this.mapToTypeScript(config.type)}`;
    });

    return `{
${interfaceProps.join(';\n')};
}`;
  }

  generateTypeInterfaces(props) {
    // Generate additional TypeScript interfaces as needed
    return `// Add custom interfaces here as needed`;
  }

  mapToTypeScript(propType) {
    const typeMap = {
      string: 'string',
      number: 'number',
      boolean: 'boolean',
      array: 'any[]',
      object: 'object',
      func: '(...args: any[]) => any'
    };
    return typeMap[propType] || 'any';
  }

  getDefaultDesignTokens() {
    return {
      spacing: [0, 4, 8, 16, 32, 64],
      colors: {
        primary: '#1976d2',
        secondary: '#dc004e',
        success: '#2e7d32',
        error: '#d32f2f'
      },
      typography: {
        fontFamily: 'Roboto, sans-serif',
        fontSize: '16px'
      }
    };
  }

  getDragDropTemplate() {
    return {
      dependencies: ['react-beautiful-dnd'],
      props: {
        items: { type: 'array', required: true },
        onDragEnd: { type: 'func', required: true }
      }
    };
  }

  getChartsTemplate() {
    return {
      dependencies: ['recharts'],
      props: {
        data: { type: 'array', required: true },
        width: { type: 'number', default: '100%' },
        height: { type: 'number', default: 400 }
      }
    };
  }

  getMuiTemplate() {
    return {
      dependencies: ['@mui/material'],
      props: {
        sx: { type: 'object' },
        variant: { type: 'string' }
      }
    };
  }

  getDefaultTemplate() {
    return {
      dependencies: ['react'],
      props: {
        children: { type: 'node' },
        className: { type: 'string' }
      }
    };
  }
}

module.exports = ScaffoldAgent;